name: Update Configs

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: sub

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip install -r requirements.lock

    - name: Update configs list
      run: python -m src.main

    - name: Sort configs
      run: python -m src.sort

    - name: Commit and push configs
      run: |
        git checkout sub
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "chore: update configs ($(date '+%Y-%m-%d %H:%M:%S'))"
        git push origin sub
